### PR TITLE
Dark Mode Bug fixed in news button 

### LINKED ISSUE #315: Dark-mode bug in News button
Issue Type:
[x] Bug Report 
[  ]  Feature Request 
[  ] Documentaion

The more news button text is not visible in darkmode 
!!

Screenshot 2021-05-27 185530

### PR DESCRIPTION
**Pull request by rohank2502**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #315 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Explain the Testing instructions

**Test Configuration**:
* Operating system:
* Version:
* Text-editors used:
 
# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [] New and existing unit tests pass locally with my changes
- [x ] Any dependent changes have been merged and published in downstream modules
# ATTACH SCREEN-SHOTS

### CODE REVIEW

**Comment by rohank2502** [comment]
@himanshu007-creator  Please have a look !

**Comment by himanshu007-creator** [comment]
> @himanshu007-creator Please have a look !

Please share the gh page link

**Comment by rohank2502** [comment]
https://rohank2502.github.io/SFC-foundations/ @himanshu007-creator

**Comment by himanshu007-creator** [comment]
> https://rohank2502.github.io/SFC-foundations/ @himanshu007-creator

Its good, please resolve more events button in similar way in this PR. Then its GTG

**Comment by rohank2502** [comment]
> resolve more events button

More event button works well are you saying about the shape of button ?

**Comment by himanshu007-creator** [comment]
the clickable part is just the orange one, resize it and make it look like the more news button

**Comment by rohank2502** [comment]
> 
> 
> 
> 
> the clickable part is just the orange one, resize it and make it look like the more news button

OK

**Pull request merged**
