### PR TITLE
new Darkmode Toggler and fix the but in it

### LINKED ISSUE #168: Make toggle button action smooth
## Issue Type:
[  ] Bug Report 
[x]  Feature Request 
[  ] Documentaion

## **Describe the bug**
As you can see in picture the toggle button is not looking good in dark mode because of its white background
sfc tg

## **Possible solution**

I can replace it with this
toggle

### PR DESCRIPTION
**Pull request by arpit456jain**
# Description

The previous darkmode toggler is good but there is a bug in it like when you activate the dark mode and  refresh the page the dark mode should be activated but you can see in this video this is not happening . because there is no code in js for handling the mode.

https://user-images.githubusercontent.com/55352601/115191668-5eaa6380-a107-11eb-97b7-69ac1eaec6f3.mp4

Fixes #168  

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
# ATTACH SCREEN-SHOTS

I had added a new dark mode toggle , write its css , and most importantly its js code for theme handling after refresh 
I have made it fully responsive as you can see full demonstration in this video.

https://user-images.githubusercontent.com/55352601/115192192-1b042980-a108-11eb-99f4-46fc8237c7d3.mp4

### CODE REVIEW

**Comment by rohank2502** [comment]
@arpit456jain  Please deploy your version on Github pages

**Review by rohank2502 — CHANGES_REQUESTED** [review]
Deploy  your code on github pages

**Comment by arpit456jain** [comment]
> Deploy your code on github pages

https://arpit456jain.github.io/coursera/index.html

**Comment by arpit456jain** [comment]
> > Deploy your code on github pages
> 
> https://arpit456jain.github.io/coursera/index.html

@rohank2502 you can check it live

**Comment by himanshu007-creator** [comment]
> > > Deploy your code on github pages
> > 
> > 
> > https://arpit456jain.github.io/coursera/index.html
> 
> @rohank2502 you can check it live

@rohank2502  do the honors, once you check it and its good to go, type LGTM

**Comment by rohank2502** [comment]
> > > > Deploy your code on github pages
> > > 
> > > 
> > > https://arpit456jain.github.io/coursera/index.html
> > 
> > 
> > @rohank2502 you can check it live
> 
> @rohank2502 do the honors, once you check it and its good to go, type LGTM

Actually I did I have commented Please word But to be short i don't mention it in Review Sorry for that

**Comment by rohank2502** [comment]
@himanshu007-creator  LGTM

**Comment by arpit456jain** [comment]
@rohank2502 kindly add suitable labels to it before merging

**Comment by rohank2502** [comment]
> @rohank2502 kindly add suitable labels to it before merging

Dont worry you will get level tag when got merged

**Comment by himanshu007-creator** [comment]
thanks @rohank2502 @arpit456jain

**Comment by arpit456jain** [comment]
@himanshu007-creator give it a level 2 tag at least as i replaced the previous toggle button and also fix the bug by writing js code

**Pull request merged**
