### PR TITLE
prototype home

### LINKED ISSUE #5: Home page

### PR DESCRIPTION
**Pull request by nisha331**
# Description
This is a prototype of the home page , all dummy texts and images are used . It is made using html CSS and bootstrap.

issue #5 #58 

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #5 #58 

## created the page from scratch.

- [x] New feature (non-breaking change which adds functionality)

 
# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
# ATTACH SCREEN-SHOTS
Screen recording - https://drive.google.com/file/d/1aIyJVEetfyE56RtGYUDVBV5StgLLnowg/view?usp=drivesdk
Capture6
Capture7
Capture4
Capture3
Capture1
Capture
Capture1

### CODE REVIEW

**Comment by nisha331** [comment]
what is progress on the PR?

**Comment by 1502shivam-singh** [comment]
@nisha331 sorry for the delayed response. 
This prototype needs some more work, firstly

img
In this one the hierarchy and contrast is a problem. The hero text is too dim to be visible against the colorful image background. Try to keep an image similar to one you will actually want in the website if thinking for a placeholder image for now.
Try raising the font weight and size for proper hierarchy and clarity. check this for explanation on [visual hierarchy](https://xd.adobe.com/ideas/process/information-architecture/visual-hierarchy-principles-examples/)
Also, the background image doesn't have much correlation with charity or saving lives per se.

And in the "about us" kind of section where you mention what we do etc. try to keep it center aligned rather than left, as you have followed this in other sections too, testimonials for example, just for consistency.

**Comment by nisha331** [comment]
@1502shivam-singh , thanks for your response , for the hero text i can  definitely do it but the thing s that that image use is just from google when we will put the image that the org will provide , we again would have to adjust it, so in my opinion we can adjust it at that time rather then doing the same thing  twice .
And regarding the about us section , according  to me its the home page so adding few img of the org will look good(though its my personal opinion).  I can bring it to center no issue but it would become a bit dull.

This were the points i had to put forward now, if you still want changes you are welcome , just look into the points and say me the changes to be done.

Thanking You
Nisha

**Comment by 1502shivam-singh** [comment]
> @1502shivam-singh , thanks for your response , for the hero text i can definitely do it but the thing s that that image use is just from google when we will put the image that the org will provide , we again would have to adjust it, so in my opinion we can adjust it at that time rather then doing the same thing twice .
> And regarding the about us section , according to me its the home page so adding few img of the org will look good(though its my personal opinion). I can bring it to center no issue but it would become a bit dull.
> 
> This were the points i had to put forward now, if you still want changes you are welcome , just look into the points and say me the changes to be done.
> 
> Thanking You
> Nisha

That's what I am saying here for the hero section. Put an image that is close to what you would actually put in the hero section, or don't put an image for now, just a color as placeholder for now. This is because, you are providing a prototype here, and I expect the prototype to be what will actually come on the website. What you have done here is mixed "Wireframe" with "Prototype".
If you are not clear on hero image for now, put an image that is close to what you will put or as above I suggested.
For the hero text, do look into it in terms of **hierarchy** and **clarity**(accessibility). 

And how exactly would centering the elements here make it look dull? To be clear, I mean centering individual elements
image

For example this - 
image

And just a suggestion, try to work more on visual design, to improve UX of the website from 10x to 100x. If you need some website suggestions for design inspiration, do ask.

**Comment by 1502shivam-singh** [comment]
I am not sure whether org would provide a hero image, so maybe try a dull photo for now, rather than something bright and colorful.

**Pull request closed without merging**
