### PR TITLE
Template

### LINKED ISSUE #245: Templates for Blog News And Events
## Issue Type:
[  ] Bug Report 
[x]  Feature Request 
[  ] Documentaion

Create a separate template page for each o blog news and events!

### PR DESCRIPTION
**Pull request by rohank2502**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #245 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Explain the Testing instructions

**Test Configuration**:
* Operating system:
* Version:
* Text-editors used:
 
# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by rohank2502** [comment]
https://rohank2502.github.io/SFC-foundations/    @himanshu007-creator  Please have a look !!

**Review by himanshu007-creator — CHANGES_REQUESTED** [review]
Here, make the img elements to only 2, rest all LGTM

**Comment by rohank2502** [comment]
> Here, make the img elements to only 2, rest all LGTM

I think that events can have many and we can adjust that na means as much we send from backend that many only tags will appear what do you think? because many events have more than 2 -3 pics and all are important events!

**Comment by himanshu007-creator** [comment]
> > Here, make the img elements to only 2, rest all LGTM
> 
> I think that events can have many and we can adjust that na means as much we send from backend that many only tags will appear what do you think? because many events have more than 2 -3 pics and all are important events!

okay, the backend guy @Aditya201551 , more work 😂💀

**Comment by Aditya201551** [comment]
@himanshu007-creator okay i will start the work now

**Pull request merged**
