### PR TITLE
Add Page Vatavaran

### LINKED ISSUE #190: Add page for vatavaran
## Issue Type:
[  ] Bug Report 
[ x]  Feature Request 
[  ] Documentaion

## **Describe the bug**

Add Page for Vatavaran Project

### PR DESCRIPTION
**Pull request by rohank2502**
# Description

Added Page Vatavaran 

Fixes #190 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Explain the Testing instructions
https://rohank2502.github.io/SFC-foundations/pages/vatavaran.html
 
# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
# ATTACH SCREEN-SHOTS
https://rohank2502.github.io/SFC-foundations/pages/vatavaran.html

### CODE REVIEW

**Comment by rohank2502** [comment]
Have a look @himanshu007-creator @SnehaVeerakumar @divyashukla23

**Review by SnehaVeerakumar — CHANGES_REQUESTED** [review]
@rohank2502 kindly add dark mode in css file.

**Comment by rohank2502** [comment]
> k mode in css file.

Yes actually Dark mode for all 3 pages fades the text I am creating a new issue for dark mode of all three pages don't worry

**Comment by SnehaVeerakumar** [comment]
@rohank2502 I am sure that you will be in top of the leaderboard 😂

**Comment by rohank2502** [comment]
> @rohank2502 I am sure that you will be in top of the leaderboard 😂

Lol don't worry will not take point for this if so :) Actually I forgot to add it then thought adding for every page at single time will be more convenient to add and review !

**Comment by SnehaVeerakumar** [comment]
And here I created the whole home page with full functionality in a single PR. I feel pity for myself😅

**Comment by SnehaVeerakumar** [comment]
> > @rohank2502 I am sure that you will be in top of the leaderboard joy
> 
> Lol don't worry will not take point for this if so :) Actually I forgot to add it then thought adding for every page at single time will be more convenient to add and review !

Not an issue, you deserve points for your work

**Comment by rohank2502** [comment]
> > > @rohank2502 I am sure that you will be in top of the leaderboard joy
> > 
> > 
> > Lol don't worry will not take point for this if so :) Actually I forgot to add it then thought adding for every page at single time will be more convenient to add and review !
> 
> Not an issue, you deserve points for your work

So can we merge this so can work on dark mode in common

**Pull request merged**
