### PR TITLE
Made Site Responsive !! 

### LINKED ISSUE #273: Responsiveness
## Issue Type:
[x ] Bug Report 
[  ]  Feature Request 
[  ] Documentaion

## **Describe the bug**

Make Website Responsive to Mobile !

### PR DESCRIPTION
**Pull request by rohank2502**
Fixes #273  

Just 2 pages are remaining KMP & Core team ! Please have a look at all pages and let me know if I missed any other than those two pages !!

https://rohank2502.github.io/SFC-foundations/     Deployment link !

### CODE REVIEW

**Comment by himanshu007-creator** [comment]
@rohank2502 Good work, but still some changes are requested,
WhatsApp Image 2021-05-17 at 4 37 09 PM
WhatsApp Image 2021-05-17 at 4 35 14 PM


The dog div is broken in some pages.
The images with text in about us section needs increment of font size.

**Comment by rohank2502** [comment]
Please Have a look at the changes made @himanshu007-creator

**Comment by himanshu007-creator** [comment]
All sorted,  just change the font size here in mobile view, and increase the image size


This issue still exist,

**Review by himanshu007-creator — APPROVED** [review]
RTM

**Pull request merged**
