### PR TITLE
Addition of contact page

### LINKED ISSUE #200: Enhancement in contact us form
## Issue Type:
     Enhancement and coding it.

## **Describe the bug**

- Present conatact form design needs UI enhancements.

## **Possible solution**

- Adding neumorphic/glassmorphic designs will enhance the form view

### PR DESCRIPTION
**Pull request by SnehaVeerakumar**
# Description

This PR creates a contact page for the website.

Fixes #200 

## Type of change
Design has been improved and code have been added.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Explain the Testing instructions

**Test Configuration**:
* Operating system: Windows
* Version: 10
* Text-editors used: VS CODE
 
# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
# ATTACH SCREEN-SHOTS
Screenshot (1107)

### CODE REVIEW

**Comment by himanshu007-creator** [comment]
@SnehaVeerakumar  please share the github pages deployment

**Comment by SnehaVeerakumar** [comment]
> @SnehaVeerakumar please share the github pages deployment

Do I need host one ?

**Comment by himanshu007-creator** [comment]
> > @SnehaVeerakumar please share the github pages deployment
> 
> Do I need host one ?

yes, you can host a github page from your repo and share the link here

**Comment by SnehaVeerakumar** [comment]
> > > @SnehaVeerakumar please share the github pages deployment
> > 
> > 
> > Do I need host one ?
> 
> yes, you can host a github page from your repo and share the link here

Okay, also I forgot to include header and footer. It will be done soon.

**Comment by SnehaVeerakumar** [comment]
https://snehaveerakumar.github.io/SFC-foundations/pages/contact/contact.html

@himanshu007-creator

**Review by himanshu007-creator — CHANGES_REQUESTED** [review]
There are some issues with your PR
1) the theme toggle button doesn't work on your page
2) increase the size of send button a little more
3) please create a mailto action similar to <a href="https://www.w3docs.com/snippets/html/how-to-create-mailto-forms.html">this</a>
4) look out for merge conflicts
for the 3rd step, you should use email as <code>sfcfoundationswebsite@gmail.com</code>

**Comment by himanshu007-creator** [comment]
> There are some issues with your PR
> 
> 1. the theme toggle button doesn't work on your page
> 2. increase the size of send button a little more
> 3. please create a mailto action similar to [this](https://www.w3docs.com/snippets/html/how-to-create-mailto-forms.html)
> 4. look out for merge conflicts
>    for the 3rd step, you should use email as `[sfcfoundationswebsite@gmail.com](mailto:sfcfoundationswebsite@gmail.com)`

@rohank2502 , you can help her in 1st problem

**Comment by rohank2502** [comment]
> > There are some issues with your PR
> > 
> > 1. the theme toggle button doesn't work on your page
> > 2. increase the size of send button a little more
> > 3. please create a mailto action similar to [this](https://www.w3docs.com/snippets/html/how-to-create-mailto-forms.html)
> > 4. look out for merge conflicts
> >    for the 3rd step, you should use email as `[sfcfoundationswebsite@gmail.com](mailto:sfcfoundationswebsite@gmail.com)`
> 
> @rohank2502 , you can help her in 1st problem

ok will do

**Comment by SnehaVeerakumar** [comment]
> > > There are some issues with your PR
> > > 
> > > 1. the theme toggle button doesn't work on your page
> > > 2. increase the size of send button a little more
> > > 3. please create a mailto action similar to [this](https://www.w3docs.com/snippets/html/how-to-create-mailto-forms.html)
> > > 4. look out for merge conflicts
> > >    for the 3rd step, you should use email as `[sfcfoundationswebsite@gmail.com](mailto:sfcfoundationswebsite@gmail.com)`
> > 
> > 
> > @rohank2502 , you can help her in 1st problem
> 
> ok will do

No, thank you. I have resolved it.

**Comment by rohank2502** [comment]
> > > > There are some issues with your PR
> > > > 
> > > > 1. the theme toggle button doesn't work on your page
> > > > 2. increase the size of send button a little more
> > > > 3. please create a mailto action similar to [this](https://www.w3docs.com/snippets/html/how-to-create-mailto-forms.html)
> > > > 4. look out for merge conflicts
> > > >    for the 3rd step, you should use email as `[sfcfoundationswebsite@gmail.com](mailto:sfcfoundationswebsite@gmail.com)`
> > > 
> > > 
> > > @rohank2502 , you can help her in 1st problem
> > 
> > 
> > ok will do
> 
> No, thank you. I have resolved it.

Great

**Comment by rohank2502** [comment]
@SnehaVeerakumar  Please check in your deployed version it's not enabling dark mode

**Comment by SnehaVeerakumar** [comment]
I haven't done the commits yet, please wait. I have got other works to do

**Comment by rohank2502** [comment]
And one suggestion regarding that blue box if we are not going to add anything below the social media icon then we can reduce its height and also it will be good if all 4 social media icons occupy all width What you think @himanshu007-creator

**Comment by rohank2502** [comment]
> I haven't done the commits yet, please wait. I have got other works to do

OK np

**Comment by SnehaVeerakumar** [comment]
> And one suggestion regarding that blue box if we are not going to add anything below the social media icon then we can reduce its height and also it will be good if all 4 social media icons occupy all width What you think @himanshu007-creator

Once the address and other details are being added by NGO, we can have a clear idea about space they need. So we can wait till they provide/update it.
We never really know how many contavt details they want to add. They can add 3 to 4 contact numbers too.

**Comment by SnehaVeerakumar** [comment]
@rohank2502 See if you can modify further in this contact page such as glassmorphism.

**Comment by rohank2502** [comment]
> rther in this contact page such as glassmorphism.

will try

**Comment by SnehaVeerakumar** [comment]
https://snehaveerakumar.github.io/SFC-foundations/pages/contact/contact.html

@himanshu007-creator

**Comment by rohank2502** [comment]
@SnehaVeerakumar  Please reduce the top margin so that scroll will not possible this will make this more better if possible

**Comment by himanshu007-creator** [comment]
> @SnehaVeerakumar Please reduce the top margin so that scroll will not possible this will make this more better if possible

yes, and on the left side, please insert a social handle for linkedin

**Comment by rohank2502** [comment]
> > @SnehaVeerakumar Please reduce the top margin so that scroll will not possible this will make this more better if possible
> 
> yes, and on the left side, please insert a social handle for linkedin

Can we increase the size of logos? it will look better I think

**Review by himanshu007-creator — COMMENTED** [review]
cant we use method="post" ?

**Comment by SnehaVeerakumar** [comment]
> cant we use method="post" ?

U have php now ?
Post in html? Is that even possible?

**Comment by himanshu007-creator** [comment]
> > cant we use method="post" ?
> 
> U have php now ?
> Post in html? Is that even possible?

i was thinking to implement, but will take time. If we go by your form, fill and submit, then again email app opens up with blank email. Expected behavior is the message user types in website carries to email

**Comment by SnehaVeerakumar** [comment]
> > > cant we use method="post" ?
> > 
> > 
> > U have php now ?
> > Post in html? Is that even possible?
> 
> i was thinking to implement, but will take time. If we go by your form, fill and submit, then again email app opens up with blank email. Expected behavior is the message user types in website carries to email

Incase if  you don't know frontend, refer this article. https://html.form.guide/email-form/html-email-form/

**Comment by SnehaVeerakumar** [comment]
In the case of unsatisfied project requirement, close this PR.

**Comment by himanshu007-creator** [comment]
Thanks for your contribution @SnehaVeerakumar , but this issue require some backwork. in case some API's can be used for this
<a href="https://formspree.io/">example </a>

**Comment by SnehaVeerakumar** [comment]
> Thanks for your contribution @SnehaVeerakumar , but this issue require some backwork. in case some API's can be used for this
> [example ](https://formspree.io/)

Too quick in figuring out, thank you.

**Pull request closed without merging**
