### PR TITLE
[MASTER] Added tribute to contributors.

### PR DESCRIPTION
**Pull request by sharathguvvala**
Added tribute to contributors feature.
Created a new HTML file in the root level of the repo with the name Tribute_To_Contributors.html, and added a link to that in the readme.
lgm tribute

### CODE REVIEW

**Review by himanshu007-creator — APPROVED** [review]
LGTM🎉

**Comment by rohan-kulkarni-25** [comment]
> 
> 
> LGTM🎉

wait

**Comment by rohan-kulkarni-25** [comment]
@sharathguvvala  You have entered origin as your username please enter the  himanshu007-creator /
SFC-foundations  in repo not name of your repository !! 

Please make changes

**Comment by sharathguvvala** [comment]
> @sharathguvvala You have entered origin as your username please enter the himanshu007-creator /
> SFC-foundations in repo not name of your repository !!
> 
> Please make changes

Yeah, it's done.

**Comment by sharathguvvala** [comment]
lgm tribute 1

I changed the repo name. But the contributors are not visible, this issue might be occurring because the himanshu007-creator/SFC-foundations repo isn't deployed through Github pages.

**Comment by himanshu007-creator** [comment]
> I changed the repo name. But a malware issue is coming and also himanshu007-creator/SFC-foundations repo isn't deployed with GitHub pages, so this might not work.
> lgm tribute 2

#418

**Pull request merged**
