### PR TITLE
Added Page Join-Us Intern 

### LINKED ISSUE #197: Add Page Join-Us Intern
## Issue Type:
[  ] Bug Report 
[ x]  Feature Request 
[  ] Documentaion

## **Describe the bug**

Add a Page of Join us in intern

### PR DESCRIPTION
**Pull request by rohank2502**
# Description

I have added a Page in Join us intern please look it in broad overview we will fix the small  changes of file location if links are broken Actually I have also added folder so it will be easy to maintain so might be some links can be broken but no issues we will get back to that in next page ! 

Fixes #197 

## Type of change

- [] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

 
# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
# ATTACH SCREEN-SHOTS

SFC FOUNDATIONS _ JOIN-US _ INTERN - Google Chrome 20-04-2021 05_33_11 PM

### CODE REVIEW

**Comment by rohank2502** [comment]
@himanshu007-creator  Please give it a look If you like the design then please get this merged we will finish the Join Us section by today or at max tomorrow noon

**Review by himanshu007-creator — CHANGES_REQUESTED** [review]
Can you restructure this?
there should be a single page of join us.
It should further have two containers. each having a picture, description and form link at end.
One box should be renamed as <code>as  intern</code> and second  <code>as  volunteer</code>

**Comment by rohank2502** [comment]
SFC FOUNDATIONS _ JOIN-US _ INTERN - Google Chrome 20-04-2021 10_00_10 PM
SFC FOUNDATIONS _ JOIN-US _ INTERN - Google Chrome 20-04-2021 09_59_59 PM


@himanshu007-creator

**Comment by himanshu007-creator** [comment]
> SFC FOUNDATIONS _ JOIN-US _ INTERN - Google Chrome 20-04-2021 10_00_10 PM
> SFC FOUNDATIONS _ JOIN-US _ INTERN - Google Chrome 20-04-2021 09_59_59 PM
> 
> @himanshu007-creator

please share deployed page.

**Comment by himanshu007-creator** [comment]
https://github.com/rohank2502/SFC-foundations/deployments/activity_log?environment=github-pages
used this, not working fine\

**Comment by rohank2502** [comment]
https://rohank2502.github.io/SFC-foundations/pages/Join-Us/joinus.html    Please have a look at this

**Review by himanshu007-creator — CHANGES_REQUESTED** [review]
please work on the anchor tag of join us option on navbar
steps to produce the issue:-
1) navigate to the beginning of website
2) click on join us option
3) notice the join us option is not visible, instead a sneak peak of two options is visible

**Pull request merged**
