### PR TITLE
Update coreteam.css

### PR DESCRIPTION
**Pull request by s-s5678**
Changes in Font and Font-styles

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue no.) 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Explain the Testing instructions

**Test Configuration**:
* Operating system:
* Version:
* Text-editors used:
 
# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
# ATTACH SCREEN-SHOTS

### CODE REVIEW

**Comment by himanshu007-creator** [comment]
@s-s5678  Please host your branch on github and share the link

**Comment by rohank2502** [comment]
Please also link on which issue you was working !

**Comment by s-s5678** [comment]
> @s-s5678 Please host your branch on github and share the link

https://s-s5678.github.io/SFC-foundations/pages/About-Us/coreteam.html

**Comment by rohank2502** [comment]
Please make it lighter 300 or 400 might look more better @himanshu007-creator  What you think ?

**Comment by s-s5678** [comment]
> Please also link on which issue you was working !

Updating the font 

> Please also link on which issue you was working !



> Please also link on which issue you was working !

issue #5

**Comment by s-s5678** [comment]
> Please make it lighter 300 or 400 might look more better @himanshu007-creator What you think ?

issue #5

**Comment by rohank2502** [comment]
> 
> 
> > Please make it lighter 300 or 400 might look more better @himanshu007-creator What you think ?
> 
> issue #5

No this is not related to that ?

**Comment by rohank2502** [comment]
> 
> 
> > Please make it lighter 300 or 400 might look more better @himanshu007-creator What you think ?
> 
> issue #5

It's ok that you make changes but these are changes we can accept if you might have done something we don't accept or don't like then this will waste your efforts so it is advised to create issue and work on that !!  Just take it as suggestion  @s-s5678

**Comment by s-s5678** [comment]
> > > Please make it lighter 300 or 400 might look more better @himanshu007-creator What you think ?
> > 
> > 
> > issue #5
> 
> It's ok that you make changes but these are changes we can accept if you might have done something we don't accept or don't like then this will waste your efforts so it is advised to create issue and work on that !! Just take it as suggestion @s-s5678

Okay sir!

**Comment by himanshu007-creator** [comment]
@s-s5678 you can work on the team chandigarh button. It should be in single line, what you can do is reduce size of all teh buttons and bold them, what do you say @rohank2502 ?

**Comment by rohank2502** [comment]
> can work on the team chandigarh butt

Can you please attach ss @himanshu007-creator  Because I am not getting where it is in 2 line

**Comment by rohank2502** [comment]
> 
> 
> > > > Please make it lighter 300 or 400 might look more better @himanshu007-creator What you think ?
> > > 
> > > 
> > > issue #5
> > 
> > 
> > It's ok that you make changes but these are changes we can accept if you might have done something we don't accept or don't like then this will waste your efforts so it is advised to create issue and work on that !! Just take it as suggestion @s-s5678
> 
> Okay sir!

You can say Rohan

**Pull request merged**
