### PR TITLE
Eventpage Added 

### LINKED ISSUE #216: Add Event Page
## Issue Type:
[  ] Bug Report 
[x]  Feature Request 
[  ] Documentaion

## **Describe the bug**

When we click more event button on main page it should take us to separate event page

### PR DESCRIPTION
**Pull request by rohank2502**
# Description

Added the Event page and linked it to More events button in Upcoming Events Section 

Fixes #216 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Explain the Testing instructions

**Test Configuration**:
* Operating system: Win 
* Version:10
* Text-editors used: VSCODE
  
# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by rohank2502** [comment]
@himanshu007-creator  Please check here https://rohank2502.github.io/SFC-foundations/

And also suggest any changes I have created a box-type model so we can easily maintain this CSS needs to be clean I will do this for every page and sort them only keep which are needed don't worry about the code base will make it clean and Please let me know about the img size should they be small or big or are they perfect

**Comment by himanshu007-creator** [comment]
@rohank2502 , please make size of event containers uniform for all and create different categories for blogs.
Insert a dropdown at top left with categories. So that when user selects a particular category, only those category blogs are visible.
categories are
1) all
2) Women Empowerment
3) education
4) environment
5) social awareness

**Comment by divyashukla23** [comment]
@rohank2502 can u attach ss for this particular PR for the changes that you have made ?

**Comment by rohank2502** [comment]
> @rohank2502 can u attach ss for this particular PR for the changes that you have made ?

Please give me time I will deploy the link @divyashukla23

**Comment by rohank2502** [comment]
@divyashukla23  Please check the deployment Please dont merge this one few changes are under work like sort feature improvement will let you know after the work gets over @himanshu007-creator Sorry for little delay in work

**Review by himanshu007-creator — CHANGES_REQUESTED** [review]
On deployment, when we go to more events, the join us page opens up, look into it and fix this.

**Comment by rohank2502** [comment]
> n we go to more events, the join us page opens up, look into it and fix this.

Yes Just the linking page is remaining

**Comment by rohank2502** [comment]
https://rohank2502.github.io/SFC-foundations/pages/Events/events.html    Everything is ok just the sort button function is not implemented I have added option to sort when we click on sort the diffrent filter gets visible but as we have not added those to particular event so this will not be working we can get that with few lines of Js and the event boxes are updated few days back so there might be some event those are not updated from orignal site do you want to update that now ? Please let me know else everything is ok !!

**Comment by himanshu007-creator** [comment]
RTM

**Review by himanshu007-creator — APPROVED** [review]

**Pull request merged**
