### PR TITLE
Darkmode to Pages

### LINKED ISSUE #195: Mode Reverts back after reload
## Issue Type:
[ x] Bug Report 
[  ]  Feature Request 
[  ] Documentaion

## **Describe the bug**

If we Put Darkmode on and Refresh Page then WE remain on darkmode after reload on main page but when we do the same on project pages then it don't happen 

## **Possible solution**

I will like to work on this!

### PR DESCRIPTION
**Pull request by rohank2502**
# Description
Added new darkmode to pages 

Fixes #195 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# Explain the Testing instructions

 
# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by rohank2502** [comment]
@himanshu007-creator  Please have a look @SnehaVeerakumar @divyashukla23

**Comment by himanshu007-creator** [comment]
> @himanshu007-creator Please have a look @SnehaVeerakumar @divyashukla23

please send GitHub pages link

**Comment by rohank2502** [comment]
> > @himanshu007-creator Please have a look @SnehaVeerakumar @divyashukla23
> 
> please send GitHub pages link

Just a min its getting deployed

**Comment by rohank2502** [comment]
> > @himanshu007-creator Please have a look @SnehaVeerakumar @divyashukla23
> 
> please send GitHub pages link

https://rohank2502.github.io/SFC-foundations/

**Review by himanshu007-creator — APPROVED** [review]
LGTM

**Pull request merged**
