### PR TITLE
added coreteam button link

### LINKED ISSUE #431: Core information link in know more
in <code>pages/About-Us/knowsfc.html</code>, the 
user will want to view the team structure of the NGO, so there should be a long button below the description

ss

solution
<a href="https://gist.github.com/himanshu007-creator/28b1e347fff2bce394a6d2ffd9bb8865">Here</a> is the starter code
Button should be enclosed in an anchor tag with link to <code>../../SFC-foundations/pages/About-Us/coreteam.html</code>

Html to go <a href="https://github.com/himanshu007-creator/SFC-foundations/blob/master/pages/About-Us/knowsfc.html">here</a>
Css to go <a href="https://github.com/himanshu007-creator/SFC-foundations/blob/master/css/About-Us/knowsfc.css">here</a> 

Note* 
This feature should be responsive as well, Please try to submit a PR soon

### PR DESCRIPTION
**Pull request by supzi-del**
# Description

Added a button to knowsfc.html within a link directed to coreteam.html, added CSS and responsiveness.

Fixes #431 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Explain the Testing instructions

**Test Configuration**:
* Operating system: Windows
* Version: 10
* Text-editors used: VScode
 
# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
# ATTACH SCREEN-SHOTS
image

### CODE REVIEW

**Comment by supzi-del** [comment]
Hey, I came across the Our goals and objective section which isn't responsive or I'm not sure what the issue is.

**Comment by himanshu007-creator** [comment]
hi @supzi-del  can you share GitHub page link of your repo?
Thanks in advance

**Comment by supzi-del** [comment]
> Hey, I came across the Our goals and objective section which isn't responsive or I'm not sure what the issue is.

I think this should be separate issue. Could you please review this current PR? :)

**Comment by himanshu007-creator** [comment]
Opening an issue for the above behaviour soon, grab it if interested🎉

**Pull request merged**
