### PR TITLE
Add source code for homepage

### LINKED ISSUE #112: Create homepage
Create an alternate to homepage which is at present <a href="http://sfcfoundations.com/">this</a>
Use <a href="https://github.com/himanshu007-creator/SFC-foundations/tree/master/Design/Homepage">this</a> file to get the design

techstack:- HTML/CSS/JS only.

Deadline :- 10 days

requirements. Create page with transactions and stuff. You also need to add a theme toggler at the top of the page.
make your code in such manner that it can be used for other pages as well. For example the header, background, footer elements will remain same, so this is a very important issue.

### PR DESCRIPTION
**Pull request by deeptea22**
# Description

I have added the HTML, CSS and JS files for the new homepage of the website using the design provided.

Fixes #112 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Explain the Testing instructions

**Test Configuration**:
* Operating system: Windows
* Version: 10 
* Text-editors used: Visual studio
 
# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
# ATTACH SCREEN-SHOTS
Screenshot (247)
Screenshot (248)
Screenshot (249)
Screenshot (250)
Screenshot (251)

### CODE REVIEW

**Comment by deeptea22** [comment]
@1502shivam-singh Please review. This is regarding the homepage of SFC. Thank you :)

**Comment by 1502shivam-singh** [comment]
@deeptea22  nice work 👏
Some questions -
Is this responsive on mobile devices too ?

Could you upload a full screen-shot of the website on mobile, as we don't have a deploy preview available on this repository yet.
(If possible, a screen-recording would be much easier)

@himanshu007-creator  look into this preview test if you can do it. For some reference on what I mean, check this - [deploy-previews](https://www.netlify.com/blog/2016/07/20/introducing-deploy-previews-in-netlify/) (This is only for netlify deployed ones, but something similar can be setup for this one too)

**Comment by deeptea22** [comment]
https://user-images.githubusercontent.com/67323371/113966096-19a34900-984c-11eb-95c4-3ab1959516a8.mp4

@1502shivam-singh @himanshu007-creator . I have attached the screen recording of the website in various devices.

**Comment by himanshu007-creator** [comment]
@deeptea22 , hi , we already have a PR for this issue, i would suggest you to work on projects page. study our present website and try to make a new project page. You can take help of the the page format in #136

**Comment by himanshu007-creator** [comment]
We are comparing your PR with #136, the one that is better will be merged

**Comment by deeptea22** [comment]
@himanshu007-creator  I was the one who commented on the issue first. Since you and the mentors asked me to work on it, I had worked on it for the past 10 days. I also made the pull request yesterday itself

**Comment by himanshu007-creator** [comment]
> @himanshu007-creator I was the one who commented on the issue first. Since you and the mentors asked me to work on it, I had worked on it for the past 10 days. I also made the pull request yesterday itself

agreed, but you need to see the fact that only the best PR will be merged. I appreciate your commitment and would like if you can work on projects page. You are half-way there already🙂

**Comment by deeptea22** [comment]
@himanshu007-creator ok thanks. I wish i could get back the time and effort i put into this for the past ten days. :)

**Comment by himanshu007-creator** [comment]
> @himanshu007-creator ok thanks. I wish i could get back the time and effort i put into this for the past ten days. :)

@deeptea , i am really sorry, there have been some miscommunication but neverminded. I really appreciate your efforts. i would like you to work on creating other pages.

> @himanshu007-creator ok thanks. I wish i could get back the time and effort i put into this for the past ten days. :)

i would suggest working on upcoming issues, i would ASSIGN YOU WHATEVER ISSUE YOU ASK FOR. really sorry on ,my part. I have experienced same thing many times, but what i learn is that, its just a job and needs to be done. doesnt matter who does it.

I respect your devotion, and i am again really sorry for this miscommunication🌸

WISH TO SEE ANOTHER PR FROM YOUR SIDE!

**Pull request closed without merging**
