### PR TITLE
Home page

### LINKED ISSUE #112: Create homepage
Create an alternate to homepage which is at present <a href="http://sfcfoundations.com/">this</a>
Use <a href="https://github.com/himanshu007-creator/SFC-foundations/tree/master/Design/Homepage">this</a> file to get the design

techstack:- HTML/CSS/JS only.

Deadline :- 10 days

requirements. Create page with transactions and stuff. You also need to add a theme toggler at the top of the page.
make your code in such manner that it can be used for other pages as well. For example the header, background, footer elements will remain same, so this is a very important issue.

### PR DESCRIPTION
**Pull request by SnehaVeerakumar**
# Description

Responsive home page of the website have been created. Starter template can be found in "Assets" folder.

Fixes #112 

# Checklist:

- [ ] Preloader
- [ ] Sticky navigation bar
- [ ] Theme toggler
- [ ] Sticky picture in right bottom corner
- [ ] Responsive
- [ ] Proper alignment

### CODE REVIEW

**Comment by himanshu007-creator** [comment]
@SnehaVeerakumar , in dark mode, the sfc logo in content is placed with a white background and it looks a bit odd. Replace this logo with a background removed image

**Comment by 1502shivam-singh** [comment]
@himanshu007-creator how was this PR merged 😕, no discussion at all, am I missing something here ? I don't see other mentors participating actively, but if I am participating, then as a mentor I prefer that the discussions are open ended and transparent.

And as you have already merged this PR, then do clarify to the other participant, who made the competing PR (still open #134) what her PR was missing and how this PR corrected that problem. Just leaving them participants in midway won't be good as she worked on it with commitment.

And do reply to this, as I have started to notice a no-reply policy from your side on my comments 😂 (JK)

**Comment by himanshu007-creator** [comment]
> @himanshu007-creator how was this PR merged 😕, no discussion at all, am I missing something here ? I don't see other mentors participating actively, but if I am participating, then as a mentor I prefer that the discussions are open ended and transparent.
> 
> And as you have already merged this PR, then do clarify to the other participant, who made the competing PR (still open #134) what her PR was missing and how this PR corrected that problem. Just leaving them participants in midway won't be good as she worked on it with commitment.
> 
> And do reply to this, as I have started to notice a no-reply policy from your side on my comments 😂 (JK)

hi @1502shivam-singh , i really appreciate your efforts and i am satisfied with your work. As a mentor you can guide participants from coding point of view ONLY. Rest decisions lie with the administration. But i would really like to thank you for your entire contribution and guidance.

**Comment by 1502shivam-singh** [comment]
> > @himanshu007-creator how was this PR merged 😕, no discussion at all, am I missing something here ? I don't see other mentors participating actively, but if I am participating, then as a mentor I prefer that the discussions are open ended and transparent.
> > And as you have already merged this PR, then do clarify to the other participant, who made the competing PR (still open #134) what her PR was missing and how this PR corrected that problem. Just leaving them participants in midway won't be good as she worked on it with commitment.
> > And do reply to this, as I have started to notice a no-reply policy from your side on my comments 😂 (JK)
> 
> hi @1502shivam-singh , i really appreciate your efforts and i am satisfied with your work. As a mentor you can guide participants from coding point of view ONLY. Rest decisions lie with the administration. But i would really like to thank you for your entire contribution and guidance.

Oh, is that so. No worries then 🙂. 
Anyway, but do tell the other participant about the PR or they will fill my DM with questions I can't answer 😂

**Comment by himanshu007-creator** [comment]
> > > @himanshu007-creator how was this PR merged 😕, no discussion at all, am I missing something here ? I don't see other mentors participating actively, but if I am participating, then as a mentor I prefer that the discussions are open ended and transparent.
> > > And as you have already merged this PR, then do clarify to the other participant, who made the competing PR (still open #134) what her PR was missing and how this PR corrected that problem. Just leaving them participants in midway won't be good as she worked on it with commitment.
> > > And do reply to this, as I have started to notice a no-reply policy from your side on my comments 😂 (JK)
> > 
> > 
> > hi @1502shivam-singh , i really appreciate your efforts and i am satisfied with your work. As a mentor you can guide participants from coding point of view ONLY. Rest decisions lie with the administration. But i would really like to thank you for your entire contribution and guidance.
> 
> Oh, is that so. No worries then 🙂.
> Anyway, but do tell the other participant about the PR or they will fill my DM with questions I can't answer 😂

😂LOL done

**Pull request merged**
