### PR TITLE
Porject page margin bug

### LINKED ISSUE #294: Margin Bug in Project Pages
## Issue Type:
[x] Bug Report 
[  ]  Feature Request 
[  ] Documentaion

We can reduce the margin to heading and navbar so that the section will be completely visible ! 

Screenshot 2021-05-20 223519

### PR DESCRIPTION
**Pull request by rohank2502**
Have reduced the margin of heading and navbar in  project pages & also in joining us pages 

Fixes #294

### CODE REVIEW

**Comment by rohank2502** [comment]
@himanshu007-creator  After Checking PR #296 I will deploy this Branch to Pages !

**Comment by himanshu007-creator** [comment]
> @himanshu007-creator After Checking PR #296 I will deploy this Branch to Pages !

Deploy!

**Comment by rohank2502** [comment]
> 
> 
> > @himanshu007-creator After Checking PR #296 I will deploy this Branch to Pages !
> 
> Deploy!

Other branch is deployed after checking that or will deploy this one

**Comment by rohank2502** [comment]
https://rohank2502.github.io/SFC-foundations/ @himanshu007-creator

**Pull request merged**
