### PR TITLE
Map integration Done

### LINKED ISSUE #163: Adding google map feature on foundation's website
## Issue Type:
Feature Request

## **Describe the bug**

It is really important to have the Google Maps Platform set up for websites to ensure your website is being seen on the web through Google's search engine.

## **Possible solution**

Adding a Google Map with a Marker to Your Website bookmark.

### PR DESCRIPTION
**Pull request by shrishti-c**
Google Map API Integration has been done in the website.

Fixes #163  

## Type of change

- [x  New feature (non-breaking change which adds functionality)

# Explain the Testing instructions

**Test Configuration**:
* Operating system: Windows
* Version: 10
* Text-editors used: VS code
 
# Checklist:
- [ x] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings
- [x ] New and existing unit tests pass locally with my changes
- 
Screenshot (187)

Please add level to this Pull Request. It will help me in my GSSOC contest.

Screenshot (186)
]

### CODE REVIEW

**Comment by himanshu007-creator** [comment]
@shrishti-c  Hi! , please deploy it on github pages and send a link here for review

**Comment by himanshu007-creator** [comment]
hi @shrishti-c please decrease the width of this map. Maybe a new IFRAME embed will work😉

**Comment by rohank2502** [comment]
> @himanshu007-creator Sure... I tried as per your instruction but that doesn't look appealing. Because with full width there seems a continuous flow in the page but after decreasing the size the it's looks more like a block even after trying several alignment option. If you still wanna have that I can update my code.

@himanshu007-creator Please have a look here

**Review by himanshu007-creator — CHANGES_REQUESTED** [review]
there is an issue. I cloned your repo and in my machine , i am unable to see any different output. Your changes are reflected well in diff , but there in no changed output. Therefore having a github page deployment is helpful. So try to make one.
@rohank2502  can guide you further , or you can take help of youtube.

**Comment by rohank2502** [comment]
> re in no changed output. Therefore having a github page deployment is helpful. So try to make one.
> @rohank2502 can guide you further , or you can take help of youtube.

@shrishti-c  Please let me know exactly what we want to do and please deploy the github pages

**Comment by shrishti-c** [comment]
Yeah Sure. I'll get it done by tomorrow. Actually I've been busy with my semester exams , so I didn't had time to learn deployment of Github.  Rest Assured. @himanshu007-creator 

@rohank2502 Thanks a lot. If I need any help, I'll reach out to you. :)

**Comment by shrishti-c** [comment]
@himanshu007-creator  https://shrishti-c.github.io/SFC-foundations/ 
Link of my deployed page.

**Comment by shrishti-c** [comment]
I found you have updated your project with my google API already so repositioned it.

**Comment by rohank2502** [comment]
@shrishti-c  Please keep the margin from both sides the same !! Left & Right!

**Comment by shrishti-c** [comment]
Screenshot (299)
Done!!! :)

**Comment by shrishti-c** [comment]
Sure, will make it responsive.

**Comment by rohank2502** [comment]
Great Work @shrishti-c  Keep IT up !! @himanshu007-creator  I think it's perfect now !!

**Comment by himanshu007-creator** [comment]
Great work @shrishti-c 🎉

**Pull request merged**
