### PR TITLE
Founderprofile Page added 

### LINKED ISSUE #215: Create Founder Page
## Issue Type:
[  ] Bug Report 
[x]  Feature Request 
[  ] Documentaion

Please suggest If changes in this design happy to make changes if they will enhance looks 

founder

### PR DESCRIPTION
**Pull request by rohank2502**
# Description

Founder Profile Page 

Fixes #215 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Explain the Testing instructions

**Test Configuration**:
* Operating system:
* Version:
* Text-editors used:
 
# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
# ATTACH SCREEN-SHOTS

### CODE REVIEW

**Comment by rohank2502** [comment]
https://rohank2502.github.io/SFC-foundations/    Made Suggested Changes please have a look at This @himanshu007-creator

**Comment by himanshu007-creator** [comment]
> https://rohank2502.github.io/SFC-foundations/ Made Suggested Changes please have a look at This @himanshu007-creator

Good work!, @rohank2502 , please do some changes, give a color to the image container( BORDER OF IMAGE I MEAN ) and secondly , introduce an animation for the know more button.
After that it is good to go.

There will be a subsequent issue to recolor border of all other people's images in website, that we will discuss later, if you are happy to work on it ' Sounds fun?!

**Comment by rohank2502** [comment]
https://rohank2502.github.io/SFC-foundations/pages/About-Us/founder.html  Please have a look @himanshu007-creator

**Comment by himanshu007-creator** [comment]
> https://rohank2502.github.io/SFC-foundations/pages/About-Us/founder.html Please have a look @himanshu007-creator

Good, @rohank2502  the transition effect is good.But i wanted an animation for the know more button. The button toggles visibility of information in an abrupt manner, it should rather have a sooth effect.

**Comment by rohank2502** [comment]
> > https://rohank2502.github.io/SFC-foundations/pages/About-Us/founder.html Please have a look @himanshu007-creator
> 
> Good, @rohank2502 the transition effect is good.But i wanted an animation for the know more button. The button toggles visibility of information in an abrupt manner, it should rather have a sooth effect.

Ok

**Comment by rohank2502** [comment]
> > https://rohank2502.github.io/SFC-foundations/pages/About-Us/founder.html Please have a look @himanshu007-creator
> 
> Good, @rohank2502 the transition effect is good.But i wanted an animation for the know more button. The button toggles visibility of information in an abrupt manner, it should rather have a sooth effect.

Please check discord message

**Comment by rohank2502** [comment]
https://rohank2502.github.io/SFC-foundations/pages/About-Us/founder.html  Have a look @himanshu007-creator

**Review by himanshu007-creator — CHANGES_REQUESTED** [review]
for pc, works fine, but same behaviour is not in mobile view
It should be same in mobile view, that bio is initially not visible, but when we scroll below, it becomes visible

**Comment by rohank2502** [comment]
Please have a look @himanshu007-creator

**Comment by himanshu007-creator** [comment]
WhatsApp Image 2021-04-26 at 12 26 15 PM

Now its good, just fix this counter for now, reduce its size and align it below the image, later on i will create a subsequent issue to reduce size of all instances of this counter

**Comment by rohank2502** [comment]
Please check once @himanshu007-creator

**Pull request merged**
