### PR TITLE
Contact us form design

### PR DESCRIPTION
**Pull request by RuchiGitHu**
# Description

I have designed a contact us page. As asked me in discord I will be raise PR for the design of other pages as well . If you find good with this PR then please merge it....

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# Explain the Testing instructions

**Test Configuration**:
* Operating system: Windows
* Version: 10
* Text-editors used: Figma wireframe
 
# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
# ATTACH SCREEN-SHOTS
contact_us form
Second_look

### CODE REVIEW

**Comment by RuchiGitHu** [comment]
> # Description
> I have designed a contact us page. As asked me in discord I will be raise PR for the design of other pages as well . If you find good with this PR then please merge it....
> 
> ## Type of change
> * [x]  New feature (non-breaking change which adds functionality)
> * [x]  This change requires a documentation update
> 
> # Explain the Testing instructions
> **Test Configuration**:
> 
> * Operating system: Windows
> * Version: 10
> * Text-editors used: Figma wireframe
> 
> # Checklist:
> * [x]  I have performed a self-review of my own code
> * [x]  I have commented my code, particularly in hard-to-understand areas
> * [x]  My changes generate no new warnings
> * [x]  New and existing unit tests pass locally with my changes
> 
> # ATTACH SCREEN-SHOTS
> contact_us form
> Second_look

@himanshu007-creator Please review. Thanks in advance

**Comment by 1502shivam-singh** [comment]
@RuchiGitHu, as I said in #114 we have discussed on a design for the homepage and the color scheme and overall design elements in this design don't match with the one's in that design.

@SAHU-01 it would be great if you work with @RuchiGitHu to provide her with the details of the homepage design (like, color scheme and typography etc.) so that she can create the "contact us" page with same design.

**Comment by RuchiGitHu** [comment]
> @RuchiGitHu, as I said in #114 we have discussed on a design for the homepage and the color scheme and overall design elements in this design don't match with the one's in that design.
> 
> @SAHU-01 it would be great if you work with @RuchiGitHu to provide her with the details of the homepage design (like, color scheme and typography etc.) so that she can create the "contact us" page with same design.

Ok, I will be glad to update my contact us page according to @SAHU-01 design.

**Comment by himanshu007-creator** [comment]
good job @RuchiGitHu

**Comment by RuchiGitHu** [comment]
> @RuchiGitHu, as I said in #114 we have discussed on a design for the homepage and the color scheme and overall design elements in this design don't match with the one's in that design.
> 
> @SAHU-01 it would be great if you work with @RuchiGitHu to provide her with the details of the homepage design (like, color scheme and typography etc.) so that she can create the "contact us" page with same design.

@SAHU-01 please let me know about font, color scheme of your design so that I can design contact us design according to that. 
Looking for your reply...

**Comment by 1502shivam-singh** [comment]
You may look into this Figma board for some background -
https://www.figma.com/proto/YzTe1JXho4W9DwcM2LLXRp/Untitled?node-id=16%3A34&frame-preset-name=Desktop&scaling=min-zoom&page-id=0%3A1

**Comment by RuchiGitHu** [comment]
> You may look into this Figma board for some background -
> https://www.figma.com/proto/YzTe1JXho4W9DwcM2LLXRp/Untitled?node-id=16%3A34&frame-preset-name=Desktop&scaling=min-zoom&page-id=0%3A1

Please review @1502shivam-singh, @himanshu007-creator 
image

**Comment by himanshu007-creator** [comment]
> > You may look into this Figma board for some background -
> > https://www.figma.com/proto/YzTe1JXho4W9DwcM2LLXRp/Untitled?node-id=16%3A34&frame-preset-name=Desktop&scaling=min-zoom&page-id=0%3A1
> 
> Please review @1502shivam-singh, @himanshu007-creator
> image

hi @ruchi, the design is good, but you can take this week, and show me the best thing possible, work on the layout. You can make it better. Align the field descriptions on one side. On left hand side, please use another picture. Next update on PR will be final. If not found satisfactory, will not be merged. Best of luck

**Comment by SnehaVeerakumar** [comment]
I would like to collaborate with @RuchiGitHu

**Comment by RuchiGitHu** [comment]
> > > You may look into this Figma board for some background -
> > > https://www.figma.com/proto/YzTe1JXho4W9DwcM2LLXRp/Untitled?node-id=16%3A34&frame-preset-name=Desktop&scaling=min-zoom&page-id=0%3A1
> > 
> > 
> > Please review @1502shivam-singh, @himanshu007-creator
> > image
> 
> hi @ruchi, the design is good, but you can take this week, and show me the best thing possible, work on the layout. You can make it better. Align the field descriptions on one side. On left hand side, please use another picture. Next update on PR will be final. If not found satisfactory, will not be merged. Best of luck

Please review @himanshu007-creator @1502shivam-singh, I have to tried to make it dynamic.
image

**Comment by RuchiGitHu** [comment]
> I would like to collaborate with @RuchiGitHu

Sorry, but my designs is already done. Even at the time of previous review my design was 80% completed and after review only some changes were required according to previous review.

**Comment by SnehaVeerakumar** [comment]
> > I would like to collaborate with @RuchiGitHu
> 
> Sorry, but my designs is already done. Even at the time of previous review my design was 80% completed and after review only some changes were required according to previous review.

Kindly check for typos in your design !

**Comment by SnehaVeerakumar** [comment]
> > I would like to collaborate with @RuchiGitHu
> 
> Sorry, but my designs is already done. Even at the time of previous review my design was 80% completed and after review only some changes were required according to previous review.

I do not have any issues with you getting the points without a collaboration but it will be good if can finalize the code. If you want, I can unassign myself. That is not an issue😅 
Now that we didn't collab, your header gets mismatched with the requirements of project..

**Comment by RuchiGitHu** [comment]
> > > I would like to collaborate with @RuchiGitHu
> > 
> > 
> > Sorry, but my designs is already done. Even at the time of previous review my design was 80% completed and after review only some changes were required according to previous review.
> 
> I do not have any issues with you getting the points without a collaboration but it will be good if we can finalize the code. If you want, I can unassign myself. That is not an issue😅
> Now that we didn't collab, your header gets mismatched with the requirements of project..

@1502shivam-singh @himanshu007-creator whole thing is depend on the mentors. They will decide what we have to do, @SnehaVeerakumar your point of view and my point of view is here, let them decide. looking forward to collaborate with you Sneha in other issues.

**Comment by SnehaVeerakumar** [comment]
> > > > I would like to collaborate with @RuchiGitHu
> > > 
> > > 
> > > Sorry, but my designs is already done. Even at the time of previous review my design was 80% completed and after review only some changes were required according to previous review.
> > 
> > 
> > I do not have any issues with you getting the points without a collaboration but it will be good if we can finalize the code. If you want, I can unassign myself. That is not an issue😅
> > Now that we didn't collab, your header gets mismatched with the requirements of project..
> 
> @1502shivam-singh @himanshu007-creator whole thing is depend on the mentors. They will decide what we have to do, @SnehaVeerakumar your point of view and my point of view is here, let them decide. looking forward to collaborate with you Sneha in other issues.

It is us who is going to work together. Admin and mentor accepted as we both are assigned to this issue. Do you not want to collaborate with me in this issue?

**Comment by RuchiGitHu** [comment]
> > > > > I would like to collaborate with @RuchiGitHu
> > > > 
> > > > 
> > > > Sorry, but my designs is already done. Even at the time of previous review my design was 80% completed and after review only some changes were required according to previous review.
> > > 
> > > 
> > > I do not have any issues with you getting the points without a collaboration but it will be good if we can finalize the code. If you want, I can unassign myself. That is not an issue😅
> > > Now that we didn't collab, your header gets mismatched with the requirements of project..
> > 
> > 
> > @1502shivam-singh @himanshu007-creator whole thing is depend on the mentors. They will decide what we have to do, @SnehaVeerakumar your point of view and my point of view is here, let them decide. looking forward to collaborate with you Sneha in other issues.
> 
> It is us who is going to work together. Admin and mentor accepted as we both are assigned to this issue. Do you not want to collaborate with me in this issue?

Apologies for this @SnehaVeerakumar, due to shortage of time now a days, I am not able to collaborate with anyone. I could collaborate with you for another issue....

**Review by rohank2502 — APPROVED** [review]
Looks attractive

**Comment by 1502shivam-singh** [comment]
@RuchiGitHu check #136 for reference on my below mentioned points (updated design for homepage),
Some points of discussion -
- Revisit #136 for navbar design, update your design's navbar according to that.
- Match up letter-spacing and font face in your design with the one in #136 
- Aim for a minimalistic design, currently the design looks to crowded with all those big "Reach out to us" images. Check out some minimalistic contact form designs for inspiration. [check these](https://dribbble.com/tags/contact_form)
- Align the field names in the contact form to the left rather than right. 
- Watch out for typos in your design (Massage->Message)
- No need for drop-shadow in "Contact us" title, but even if you want to add it try positioning the drop shadow in a more visually appealing way. Maybe you can try drop shadow on the rectangular field's for a nice elevation effect, though I am not absolutely sure whether if this would look good, so, optional for now.

And @rohank2502 do check the background of the PR and discuss before approving, there are still some points to cover.

**Comment by rohank2502** [comment]
> @RuchiGitHu check #136 for reference on my below mentioned points (updated design for homepage),
> Some points of discussion -
> 
> * Revisit #136 for navbar design, update your design's navbar according to that.
> * Match up letter-spacing and font face in your design with the one in #136
> * Aim for a minimalistic design, currently the design looks to crowded with all those big "Reach out to us" images. Check out some minimalistic contact form designs for inspiration. [check these](https://dribbble.com/tags/contact_form)
> * Align the field names in the contact form to the left rather than right.
> * Watch out for typos in your design (Massage->Message)
> * No need for drop-shadow in "Contact us" title, but even if you want to add it try positioning the drop shadow in a more visually appealing way. Maybe you can try drop shadow on the rectangular field's for a nice elevation effect, though I am not absolutely sure whether if this would look good, so, optional for now.
> 
> And @rohank2502 do check the background of the PR and discuss before approving, there are still some points to cover.

Yes I just said It is looking attractive

**Comment by SAHU-01** [comment]
//cc @RuchiGitHu  sorry I could not respond earlier,as I was stuck up with another project,If you need any help or if the mentors want to assist her with the initial homepage colors and original designs I can do it, Let me know!!
From what I saw above the navbar on the initial page is a bit different, so I can provide you with the initial navbar design and those images used there.

And I don't know if I have the liberty to suggest the assigned person,but it would be great if you went through the original designs' footer section,I made a contact us there ,so rather than making two photocards we can one photocard, The frame below is just a suggestion for reference ,it's totally  your desicion Ruchi.

Add a heading

**Comment by RuchiGitHu** [comment]
> //cc @RuchiGitHu sorry I could not respond earlier,as I was stuck up with another project,If you need any help or if the mentors want to assist her with the initial homepage colors and original designs I can do it, Let me know!!
> From what I saw above the navbar on the initial page is a bit different, so I can provide you with the initial navbar design and those images used there.
> 
> And I don't know if I have the liberty to suggest the assigned person,but it would be great if you went through the original designs' footer section,I made a contact us there ,so rather than making two photocards we can one photocard, The frame below is just a suggestion for reference ,it's totally your desicion Ruchi.
> 
> Add a heading

Thanks for your suggestion and for your referenced content. I will do as reviewed to me and will take care of your suggestion also in my mind while designing.
Thanks again to helping hands.....

**Comment by SnehaVeerakumar** [comment]
@RuchiGitHu  Kindly wait before designing it. I don't want to waste your time. I have planned to make all the forms of this website to be neumorphic.
   At last don't complaint that we have wasted your time.

**Comment by RuchiGitHu** [comment]
> > @RuchiGitHu check #136 for reference on my below mentioned points (updated design for homepage),
> > Some points of discussion -
> > 
> > * Revisit #136 for navbar design, update your design's navbar according to that.
> > * Match up letter-spacing and font face in your design with the one in #136
> > * Aim for a minimalistic design, currently the design looks to crowded with all those big "Reach out to us" images. Check out some minimalistic contact form designs for inspiration. [check these](https://dribbble.com/tags/contact_form)
> > * Align the field names in the contact form to the left rather than right.
> > * Watch out for typos in your design (Massage->Message)
> > * No need for drop-shadow in "Contact us" title, but even if you want to add it try positioning the drop shadow in a more visually appealing way. Maybe you can try drop shadow on the rectangular field's for a nice elevation effect, though I am not absolutely sure whether if this would look good, so, optional for now.
> > 
> > And @rohank2502 do check the background of the PR and discuss before approving, there are still some points to cover.
> 
> Yes I just said It is looking attractive

Please check @himanshu007-creator @1502shivam-singh, I have made changes according to that.
image

**Comment by SnehaVeerakumar** [comment]
Allign "submit" properly
Remove the picture
Remove "Your"
Align everything to center
Make sure it works fine for dark mode.

@RuchiGitHu

**Comment by RuchiGitHu** [comment]
> Allign "submit" properly
> Remove the picture
> Remove "Your"
> Align everything to center
> Make sure it works fine for dark mode.
> 
> @RuchiGitHu

Please check @SnehaVeerakumar, thanks for your support...
image

**Comment by 1502shivam-singh** [comment]
> image

Final remarks -
- Match fonts of "message" with phone no. and others. Also, avoid using "Phone no.", write complete words.
- Left align Submit button with the fields.
- Remove those colons, no need
- Watch for font uniformity or match up fonts that look good. This is for the "Contact Us" title. Either make it of the same font as email address and increase it size and apply some weight OR do the same thing but with different font.
- Don't exaggerate the corner radii of the fields. Make it subtle. Similarly for the submit button.

For a better example, here's a example form I just designed in nimble time (Didn't hope I would need to do this, but anyway 😅) 

image
Don't focus on colors, rest what I mentioned above, you can see in this.
This is most likely is final review, and after these issues are solved, @himanshu007-creator merge this.

**Comment by RuchiGitHu** [comment]
> > image
> 
> Final remarks -
> 
> * Match fonts of "message" with phone no. and others. Also, avoid using "Phone no.", write complete words.
> * Left align Submit button with the fields.
> * Remove those colons, no need
> * Watch for font uniformity or match up fonts that look good. This is for the "Contact Us" title. Either make it of the same font as email address and increase it size and apply some weight OR do the same thing but with different font.
> * Don't exaggerate the corner radii of the fields. Make it subtle. Similarly for the submit button.
> 
> For a better example, here's an example form I just designed in quick time (Didn't hope I would need to do this, but anyway 😅)
> 
> image
> Don't focus on colors, rest what I mentioned above, you can see in this.
> This is most likely is final review, and after these issues are solved, @himanshu007-creator merge this.

Thanks for your review @1502shivam-singh. I have made changes again to match requirements...
image

**Comment by himanshu007-creator** [comment]
@RuchiGitHu  Great!, just do one last thing, create github pages and link this page to contact us button.
send the link here

**Comment by RuchiGitHu** [comment]
> @RuchiGitHu Great!, you wont be working on the coding part right?

Yes.

**Pull request merged**
