### PR TITLE
Layout

### LINKED ISSUE #435: Changing UI/UX design of the home page
## Issue Type:

- [x]   Feature Request 

## **Describe the bug**
The home page is not according to the UI design , everything is blended

## **Possible solution**
1. Breaking the sections into sub-sections so that they look more eye-catching 
2. Changing the layout so that everything looks much more arranged

## **Screenshots**
image

image

### PR DESCRIPTION
**Pull request by gunjan-g**
# Description
Created different sections and changed UI/UX design

Fixes #435 

## Type of change
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Explain the Testing instructions

**Test Configuration**:
* Operating system: Windows
* Version: 10
* Text-editors used: VS Code
 
# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

# ATTACH SCREEN-SHOTS
image

image

### CODE REVIEW

**Comment by gunjan-g** [comment]
@himanshu007-creator why it is showing 80 commits when I made a PR

**Comment by himanshu007-creator** [comment]
> @himanshu007-creator why it is showing 80 commits when I made a PR

This is because you have made changes to the master branch and pushing them to the development branch.
So all the changes there were not in development branch are being shown here as various commits. Its completely fine.
What you can do now is deploy your branch on GitHub pages and share the link here

**Comment by gunjan-g** [comment]
> > @himanshu007-creator why it is showing 80 commits when I made a PR
> 
> This is because you have made changes to the master branch and pushing them to the development branch.
> So all the changes there were not in development branch are being shown here as various commits. Its completely fine.
> What you can do now is deploy your branch on GitHub pages and share the link here

ok, just sharing

**Comment by gunjan-g** [comment]
@himanshu007-creator Here is the link:
https://gunjan-g.github.io/SFC-foundations/

**Review by himanshu007-creator — COMMENTED** [review]
LGTM🎉

**Comment by himanshu007-creator** [comment]
thanks @gunjan-g  for the PR and welcome to the project🎉

**Comment by gunjan-g** [comment]
> thanks @gunjan-g for the PR and welcome to the project🎉

thank you very much, would like to contribute more 😄

**Pull request merged**
