### PR TITLE
Kmp Page 

### LINKED ISSUE #233: Add KMP option
# KMP(Key Managerial Personnel)
In our NGO, there are some independent organs that dont come under a particular unit or project. We would like to make a separate page for them. It will  include
1) IC BOARD 
2) WMS ( website management system )
3) Others.. ( will discuss)

### PR DESCRIPTION
**Pull request by rohank2502**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #233 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Explain the Testing instructions

**Test Configuration**:
* Operating system:
* Version:
* Text-editors used:
 
# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
# ATTACH SCREEN-SHOTS

https://rohank2502.github.io/SFC-foundations/pages/KMP/kmp.html

### CODE REVIEW

**Comment by rohank2502** [comment]
@himanshu007-creator  Have a look at the KMP page Please !! WE will add the images to this page when we will get done with the core team page because no point to add images 2times !!

**Comment by himanshu007-creator** [comment]
> @himanshu007-creator Have a look at the KMP page Please !! WE will add the images to this page when we will get done with the core team page because no point to add images 2times !!

everything's cool, but some changes
1) change the box-shadow of managing director to differentiate her from others.
2) introduce the bio feature below, like we had in core team page

**Comment by rohank2502** [comment]
> 2\. e bio feature below, like we had in core team p

For everyone ? Or only to director

**Comment by himanshu007-creator** [comment]
> > 2. e bio feature below, like we had in core team p
> 
> For everyone ? Or only to director

everyone

**Comment by rohank2502** [comment]
Did Changes we will add the Bio and Images while merging the core team !! Will that be ok!

**Comment by himanshu007-creator** [comment]
@rohank2502 Rohan , last changes, here, please add KMP option in  about us section and remove from navbar.
and on the KMP page, change KMP heading to  Key Managerial Personnel

**Comment by rohank2502** [comment]
> @rohank2502 Rohan , last changes, here, please add KMP option in about us section and remove from navbar.
> and on the KMP page, change KMP heading to Key Managerial Personnel

Please check  the changes !

**Pull request merged**
