### PR TITLE
Added Page  Objectives

### LINKED ISSUE #206: Create Page Objectives
## Issue Type:
[  ] Bug Report 
[x]  Feature Request 
[  ] Documentaion

## **Describe the bug**
Create Page Objectives and vision

### PR DESCRIPTION
**Pull request by rohank2502**
# Description
Added Page Objectives 

Fixes #206 
 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

 
# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
# ATTACH SCREEN-SHOTS
https://rohank2502.github.io/SFC-foundations/pages/About-Us/objectives.html

### CODE REVIEW

**Comment by rohank2502** [comment]
@himanshu007-creator  Please Have a look when you are free do suggest changes

**Comment by 1502shivam-singh** [comment]
> # ATTACH SCREEN-SHOTS
> https://rohank2502.github.io/SFC-foundations/pages/About-Us/objectives.html

Link doesn't work yet, check again.

**Comment by rohank2502** [comment]
> > # ATTACH SCREEN-SHOTS
> > https://rohank2502.github.io/SFC-foundations/pages/About-Us/objectives.html
> 
> Link doesn't work yet, check again.

Yes because it was deployed for master just give me a min

**Comment by rohank2502** [comment]
Yes @himanshu007-creator  @1502shivam-singh  Please give a look its working

**Pull request merged**
