### PR TITLE
Hompage-Design Wireframe Screen shots  Attached

### PR DESCRIPTION
**Pull request by SAHU-01**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue no.) 

## Type of change

- [ x] New feature (non-breaking change which adds functionality)

# Explain the Testing instructions

**Test Configuration**:
* Operating system: Windows
* Version:
* Text-editors used: Vs Code
 
# Checklist:

- [x ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings

# ATTACH SCREEN-SHOTS

**I've attached the wireframe of the homepage As Instructed and added the screen shorts int he homepage folder inside wp-content inside the present source code.

here are the screen shorts of my design**

p1
p2
p3

regarding the footer I had certain doubts and wanted to know your preferences so when you let me know your thoughts I'll work on that part .
I
f you approve of this style and after you assign me with this task , i'll start working on the codeing part.

### CODE REVIEW

**Comment by 1502shivam-singh** [comment]
@SAHU-01 Some issues -

1) Reduce size of logo and "SFC Foundation" text in navbar. It's too big and attracts way too much attention, we want the hero section and call-to-action buttons to be of highest priority and hierarchy.

2) The hero section **lacks hierarchy**, **is too textual** (Keep copywriting concise) and **doesn't present the CTA buttons**. Along with keeping the CTA buttons in the navbar, present them in the hero section too as the main task here is to get more volunteers or donation for taking the initiative further.
For hierarchy, try contrasting font sizes and font weights. 
Hero image looks good, try to use it in a more creative way.

3) Do design other sections relating to "Events" and testimonials too.

Some websites you can take inspiration from  - 
https://www.gatesfoundation.org/
https://acumen.org/
https://www.charitywater.org/  etc.

look up charity or foundations websites for inspirations.

**Comment by 1502shivam-singh** [comment]
And next time, do tag a mentor or admin for faster response.

**Comment by SAHU-01** [comment]
Ok, so if I have to prioritize the donate and volunteer option more I can dedicate the entire hero section to that stuff, because then it would be prominent enough , it will be similar to the charity waters website ! ,If you agree to that I'll make those changes.

and comeing to the logo should I also reduce the size of of the foundation name as well.


For the events part , I'll surely work on it 

as for the footer I had raised some doubts , could you clarify them, so that I can include it in the new wireframe and this time i'll be shareing a Balsamiq link for wireframe and a prototype .

And one last query ,what are your thoughts on website theme like do want it to be something professional or something more of UI stuff kind .

/cc @1502shivam-singh @himanshu007-creator @AnkushSinghGandhi @praveenscience

**Comment by himanshu007-creator** [comment]
> Ok, so if I have to prioritize the donate and volunteer option more I can dedicate the entire hero section to that stuff, because then it would be prominent enough , it will be similar to the charity waters website ! ,If you agree to that I'll make those changes.
> 
> and comeing to the logo should I also reduce the size of of the foundation name as well.
> 
> For the events part , I'll surely work on it
> 
> as for the footer I had raised some doubts , could you clarify them, so that I can include it in the new wireframe and this time i'll be shareing a Balsamiq link for wireframe and a prototype .
> 
> And one last query ,what are your thoughts on website theme like do want it to be something professional or something more of UI stuff kind .
> 
> /cc @1502shivam-singh @himanshu007-creator @AnkushSinghGandhi @praveenscience

more UI kind of stuff, it should feel friendly(😀 )

**Comment by SAHU-01** [comment]
ok got that !
by tommorow morning i'll share the new designs.

**Comment by SAHU-01** [comment]
Well if I'm adding the volunteer ,donate feature in the hero section then for the existent hero section ,I'll put it in the homepage below with a similar style of carousel.

image


What do you think?

/cc @1502shivam-singh @himanshu007-creator @AnkushSinghGandhi @praveenscience

**Comment by SAHU-01** [comment]
here is the link to the new wireframe

https://balsamiq.cloud/swd5p85/psncvs9

I'll make the final  prototype once you agree to the arrangement of features present in this wireframe ,
and for the hero sectiion I'd suggest we should add a short video or gif and keep a similar looking donate box.

and I've added a fat footer style here so that the recent events can show up there along with social icons,etc.

/cc @1502shivam-singh @himanshu007-creator @AnkushSinghGandhi @praveenscience

**Comment by 1502shivam-singh** [comment]
Wireframe looks good, @SAHU-01 . 
And good suggestion of short video/GIF in Hero section. It needs visual design work. If we don't get some video from the foundation, images can also be utilized in hero section, but this is an afterthought for now.
Also, the child image in hero section can be utilized somewhere else, or if you have some better ideas.

**Comment by SAHU-01** [comment]
new commits are made to the previous pull request now the website looks like this

**Pull request closed without merging**
