### PR TITLE
Added Page Sampuran 

### LINKED ISSUE #180: Create Page For Sampuran Project !
## Issue Type:
[  ] Bug Report 
[x]  Feature Request 
[  ] Documentaion

Create a page for Sampuran Project

### PR DESCRIPTION
**Pull request by rohank2502**
Fixes #180

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Explain the Testing instructions

Can check on my Git pages 
https://rohank2502.github.io/SFC-foundations/pages/Sampuran.html
 
# Checklist:

- [x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ x] I have added tests that prove my fix is effective or that my feature works
- [ x New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
# ATTACH SCREEN-SHOTS
https://rohank2502.github.io/SFC-foundations/pages/Sampuran.html

### CODE REVIEW

**Comment by rohank2502** [comment]
@himanshu007-creator  Sorry for so many commits but final commit is alright you can check for deployment here https://rohank2502.github.io/SFC-foundations/pages/Sampuran.html @SnehaVeerakumar

**Comment by himanshu007-creator** [comment]
@SnehaVeerakumar  , please review the PR and suggest the changes required.

**Comment by rohank2502** [comment]
@himanshu007-creator  Sorry for delay But I will complete all three pages till Sunday Evening 👍🏻

**Comment by rohank2502** [comment]
Made changes @himanshu007-creator @SnehaVeerakumar @divyashukla23  Give it a look

**Pull request merged**
